# cloudbuild.yaml

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: DeployCloudFunction
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - store-order-data
      - --gen2
      - --region=${_REGION}
      - --runtime=python312
      - --source=functions/store_order_data
      - --entry-point=store_order_data
      - --trigger-topic=prestashop-order-data
      - --memory=256Mi
      - --timeout=30s
      - --set-env-vars=FIRESTORE_EMULATOR_HOST=
