options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Deploy Pub/Sub triggered function
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: DeployStoreOrderData
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - store-order-data
      - --gen2
      - --region=${_REGION}
      - --runtime=python312
      - --source=functions/store_order_data
      - --entry-point=store_order_data   # ✅ corregido (sin guion)
      - --trigger-topic=prestashop-order-data
      - --memory=256Mi
      - --timeout=30s
      - "--set-env-vars=FUNCTION_TARGET=store_order_data"

  # Step 2: Deploy Firestore triggered function
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: DeployNotifierOrderMilestone
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - notifier-order-milestone
      - --gen2
      - --region=${_REGION}
      - --runtime=python312
      - --source=functions/notifier_order_milestone
      - --entry-point=notifier_order_milestone
      # --- Firestore trigger (válido en Gen2) ---
      - --trigger-event-filters=type=google.cloud.firestore.document.v1.updated
      - --trigger-event-filters=database=(default)
      - --trigger-event-filters=resource=documents/orders/{order_id}
      # --- Configuration ---
      - --memory=256Mi
      - --timeout=30s
      - "--set-env-vars=FUNCTION_TARGET=notifier_order_milestone"
