substitutions:
  _REGION: europe-southwest1

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: DeployStoreOrderData
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - store-order-data
      - --gen2
      - --region=${_REGION}
      - --runtime=python312
      - --source=functions/store_order_data
      - --entry-point=store_order_data
      - --trigger-topic=prestashop-order-data
      - --memory=256Mi
      - --timeout=30s

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: DeployNotifierOrderMilestone
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - notifier-order-milestone
      - --gen2
      - --region=${_REGION}
      - --runtime=python312
      - --source=functions/notifier_order_milestone
      - --entry-point=notifier_order_milestone
      - --trigger-event-filters=type=google.cloud.firestore.document.v1.written
      - --trigger-event-filters=database=(default)
      - --trigger-event-filters-path-pattern=document=orders/{orderId}
      - --memory=256Mi
      - --timeout=30s      