options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: DeployStoreOrderData
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - store-order-data
      - --gen2
      - --region=${_REGION}              # puedes mantener europe-southwest1
      - --runtime=python312
      - --source=functions/store_order_data
      - --entry-point=store_order_data   # ✅ corregido (sin guion)
      - --trigger-topic=prestashop-order-data
      - --memory=256Mi
      - --timeout=30s
      - "--set-env-vars=FUNCTION_TARGET=store_order_data"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: DeployNotifierOrderMilestone
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - notifier-order-milestone
      - --gen2
      - --region=eur3                     # ✅ región de tu base de datos Firestore
      - --runtime=python312
      - --source=functions/notifier_order_milestone
      - --entry-point=notifier_order_milestone
      # --- Firestore trigger (formato correcto para Gen 2 / Eventarc) ---
      - --trigger-event-filters=type=google.cloud.firestore.document.v1.updated
      - --trigger-event-filters=database=(default)
      - --trigger-event-filters-path-pattern=document=documents/orders/{orderId}
      # --- Configuración general ---
      - --memory=256Mi
      - --timeout=30s
      - "--set-env-vars=FUNCTION_TARGET=notifier_order_milestone"
