services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev 
    container_name: lstotem_web
    volumes:
      - ./web:/var/www/html
      - /var/www/html/var
      - /var/www/html/vendor
    ports:
      - "8081:8081"
    restart: always
    networks:
      - lstotem-net
    env_file:
      - .env

  store-data:
    build:
      context: ./functions/store_data
      dockerfile: Dockerfile.dev
    container_name: lstotem_store-data
    depends_on:
      firestore-emulator:
        condition: service_healthy 
    volumes:
      - ./functions/store_data:/app
    ports:
      - "8080:8080"
    restart: always
    environment:
      FIRESTORE_EMULATOR_HOST: "firestore-emulator:8080"
      PUBSUB_EMULATOR_HOST: "firestore-emulator:8085"
      GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}
      FUNCTION_TARGET: store_data
      PYTHONUNBUFFERED: "1"
    networks:
      - lstotem-net
    env_file:
      - .env
  
  should-push-data:
    build:
      context: ./functions/should_push_data
      dockerfile: Dockerfile.dev
    container_name: lstotem_should-push-data
    depends_on:
      firestore-emulator:
        condition: service_healthy
    volumes:
      - ./functions/should_push_data:/app
    ports:
      - "8083:8080"
    restart: always
    environment:
      FIRESTORE_EMULATOR_HOST: "firestore-emulator:8080"
      PUBSUB_EMULATOR_HOST: "firestore-emulator:8085"
      GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}
      FUNCTION_TARGET: should_push_data
      PYTHONUNBUFFERED: "1"
      PUSHER_APP_ID: ${PUSHER_APP_ID}
      PUSHER_APP_KEY: ${PUSHER_APP_KEY}
      PUSHER_APP_SECRET: ${PUSHER_APP_SECRET}
      PUSHER_CLUSTER: ${PUSHER_CLUSTER}
    networks:
      - lstotem-net
    env_file:
      - .env

  # Firestore emulator (ephemeral; no persistence)
  firestore-emulator:
    build:
      context: . # Build from the root where Dockerfile.firebase-emulator and firebase.json are
      dockerfile: Dockerfile.firebase-emulator
    container_name: lstotem_firebase_emulator_suite
    ports:
      - "4000:4000" # Firebase Emulator UI
      - "5001:5001" # Functions Emulator
      - "8082:8080" # Firestore Emulator (mapping 8080 internal to 8082 external)
      - "8085:8085" # Pub/Sub Emulator
      - "9099:9099" # Auth Emulator
    environment:
      GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}
    networks:
      - lstotem-net
    env_file:
      - .env
    healthcheck:
      # Check if the UI is up, indicating the suite is largely ready
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 45s

networks:
  lstotem-net:
    driver: bridge